
[meta]
results_dir = "/eos/user/a/ayeagle/H_mumu/results/DNN"
use_cuda = true

[dataset]
equalize_for_training = true
equalize_per_process = false
renorm_inputs = true
signal_types = ['VBFHto2Mu', 'GluGluHto2Mu']
max_jets = 4
abs_train_weight = false
data_columns = [
    'VBFNet_Output',
    'mu1_eta',
    'mu1_pt',
    'mu2_eta',
    'mu2_pt',
    'dR_mumu',
    'm_mumu',
    'eta_mumu',
    'cosTheta_CS',
    'phi_mumu',
    'pt_mumu',
    'y_mumu',
    'phi_CS',
    'FilteredJet_pt_1', 
    'FilteredJet_pt_2', 
    'FilteredJet_pt_3',
    'FilteredJet_pt_4', 
    'FilteredJet_eta_1', 
    'FilteredJet_eta_2',
    'FilteredJet_eta_3', 
    'FilteredJet_eta_4', 
    'FilteredJet_phi_1', 
    'FilteredJet_phi_2',
    'FilteredJet_phi_3', 
    'FilteredJet_phi_4',
    'SoftActivityJetHT',
    'SoftActivityJetHT2',
    'SoftActivityJetHT5',
    'SoftActivityJetHT10',
]

[splitting]
validation_size = 0.25
k = 4

[network]  
# Hidden layers only, input layer size pulled from the used columns
layer_list = [64, 64, 32, 32]
batch_renorm = false
dropout = 0.00

[training]
batch_size = 10000
epochs = 40
early_stop = true
patience = 10

[optimizer]
algo = "Adam"   # Currently, SGD and Adam are supported
lr = 0.0001
weight_decay = 0.0

[testing]
# Number of bins for all histograms
n_bins = 24


