meta_data:
  global_config: /afs/cern.ch/user/a/ayeagle/H_mumu/config/global.yaml
  output_folder: /eos/user/a/ayeagle/H_mumu/root_files/v4_VBFNet_samples/
  input_folder: /eos/user/e/eusebi/Hmumu/anaTuples/v4_20Nov_NewJetIDs_LooseMuons/

sample_list:
  - DY
  - EWK
  - GluGluHto2Mu
  - VBFHto2Mu

