meta_data:
  global_config: /afs/cern.ch/user/a/ayeagle/H_mumu/config/global.yaml
  columns_config: /afs/cern.ch/user/a/ayeagle/H_mumu/Studies/DNN/configs/columns_config.yaml
  output_folder: /eos/user/a/ayeagle/H_mumu/root_files/v4_parse1/
  input_folder: /eos/user/e/eusebi/Hmumu/anaTuples/v4_20Nov_NewJetIDs_LooseMuons
  selection_cut: ((Signal_Fit) || (H_sideband)) & (baseline_muonJet)

sample_list:
  - DY
  - TT
  - EWK
  - VV
  - GluGluHto2Mu
  - VBFHto2Mu
